# Generated by Django 3.1.1 on 2020-09-04 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZenSlackChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=22)),
                ('chat_id', models.CharField(max_length=20)),
                ('ticket_id', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('opened', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('closed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('channel_id', 'chat_id')},
            },
        ),
    ]
