# Generated by Django 3.1.1 on 2020-09-16 15:00

from django.db import migrations, models
import zenslackchat.models


class Migration(migrations.Migration):

    dependencies = [
        ('zenslackchat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZendeskApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=512)),
                ('access_type', models.CharField(max_length=50)),
                ('scopes', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=zenslackchat.models.utcnow)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=zenslackchat.models.utcnow),
        ),
    ]
