# Generated by Django 3.1.1 on 2020-09-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zenslackchat', '0003_auto_20200916_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zendeskapp',
            name='access_type',
        ),
    ]
