# Generated by Django 3.1.1 on 2020-09-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zenslackchat', '0004_remove_zendeskapp_access_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zendeskapp',
            old_name='scopes',
            new_name='scope',
        ),
    ]
