# Generated by Django 3.1.1 on 2020-09-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zenslackchat', '0005_auto_20200916_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='SlackApp',
        ),
    ]
