# Generated by Django 3.1.2 on 2020-10-23 12:15

from django.db import migrations, models
import zenslackchat.models


class Migration(migrations.Migration):

    dependencies = [
        ('zenslackchat', '0006_auto_20200917_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagerDutyApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=512)),
                ('token_type', models.CharField(max_length=50)),
                ('scope', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=zenslackchat.models.utcnow)),
            ],
        ),
    ]
