# Generated by Django 3.1.7 on 2021-03-11 11:57

from django.db import migrations, models
import zenslackchat.models


class Migration(migrations.Migration):

    dependencies = [
        ('zenslackchat', '0007_pagerdutyapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutOfHoursInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2048)),
                ('created_at', models.DateTimeField(default=zenslackchat.models.utcnow)),
            ],
        ),
    ]
