# Generated by Django 3.1.7 on 2021-03-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenslackchat', '0009_auto_20210311_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outofhoursinformation',
            name='message',
            field=models.TextField(),
        ),
    ]
