version: 2
jobs:
    build:
        docker:
            - image: python:3.8      
            - image: redis:5
            - image: postgres:9.6
              environment:
                POSTGRES_DB: service
                POSTGRES_USERNAME: service
                POSTGRES_PASSWORD: service
                POSTGRES_HOST_AUTH_METHOD: trust
      
        environment:
            REDIS_URL: postgresql://service:service@localhost:5432/service
            DATABASE_URL: redis://localhost/
            DEBUG_ENABLED: True
            DJANGO_SETTINGS_MODULE: webapp.settings
            SECRET_KEY: c0b395ac13212cb5251c5f55eab9ed8a518ce7793c9971076153860bab4e0290
            ALLOWED_HOSTS: localhost,localhost:8000
            
        working_directory: ~/app

        steps:
            - checkout

            - restore_cache:
                name: Restore pip cache
                keys:
                  - v1-zenslackchat-{{ checksum "requirements-test.txt" }}
                  - v1-zenslackchat-
                paths:
                  - ~/cache/pip
      
            - run:
                name: Install dependencies
                command: python -m pip install --cache-dir ~/cache/pip -r requirements-test.txt
      
            - save_cache:
                name: Save pip cache
                key: v1-zenslackchat-{{ checksum "requirements-test.txt" }}
                paths:
                  - ~/cache/pip
      
            - run:
                name: Run tests
                command: make test
    